//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Apply) DeepCopyInto(out *Apply) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Apply.
func (in *Apply) DeepCopy() *Apply {
	if in == nil {
		return nil
	}
	out := new(Apply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autoscaler) DeepCopyInto(out *Autoscaler) {
	*out = *in
	if in.PatchTargetRef != nil {
		in, out := &in.PatchTargetRef, &out.PatchTargetRef
		*out = new(PatchTargetRef)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]AutoscalerMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autoscaler.
func (in *Autoscaler) DeepCopy() *Autoscaler {
	if in == nil {
		return nil
	}
	out := new(Autoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerContainerResource) DeepCopyInto(out *AutoscalerContainerResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerContainerResource.
func (in *AutoscalerContainerResource) DeepCopy() *AutoscalerContainerResource {
	if in == nil {
		return nil
	}
	out := new(AutoscalerContainerResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerExternal) DeepCopyInto(out *AutoscalerExternal) {
	*out = *in
	in.AutoscalerIdentifier.DeepCopyInto(&out.AutoscalerIdentifier)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerExternal.
func (in *AutoscalerExternal) DeepCopy() *AutoscalerExternal {
	if in == nil {
		return nil
	}
	out := new(AutoscalerExternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerIdentifier) DeepCopyInto(out *AutoscalerIdentifier) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerIdentifier.
func (in *AutoscalerIdentifier) DeepCopy() *AutoscalerIdentifier {
	if in == nil {
		return nil
	}
	out := new(AutoscalerIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerMetrics) DeepCopyInto(out *AutoscalerMetrics) {
	*out = *in
	if in.ContainerResource != nil {
		in, out := &in.ContainerResource, &out.ContainerResource
		*out = new(AutoscalerContainerResource)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(AutoscalerExternal)
		(*in).DeepCopyInto(*out)
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(AutoscalerObject)
		(*in).DeepCopyInto(*out)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(AutoscalerPods)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(AutoscalerResource)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(AutoscalerTarget)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerMetrics.
func (in *AutoscalerMetrics) DeepCopy() *AutoscalerMetrics {
	if in == nil {
		return nil
	}
	out := new(AutoscalerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerObject) DeepCopyInto(out *AutoscalerObject) {
	*out = *in
	in.AutoscalerIdentifier.DeepCopyInto(&out.AutoscalerIdentifier)
	out.DescribedObject = in.DescribedObject
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerObject.
func (in *AutoscalerObject) DeepCopy() *AutoscalerObject {
	if in == nil {
		return nil
	}
	out := new(AutoscalerObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerPods) DeepCopyInto(out *AutoscalerPods) {
	*out = *in
	in.AutoscalerIdentifier.DeepCopyInto(&out.AutoscalerIdentifier)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerPods.
func (in *AutoscalerPods) DeepCopy() *AutoscalerPods {
	if in == nil {
		return nil
	}
	out := new(AutoscalerPods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerResource) DeepCopyInto(out *AutoscalerResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerResource.
func (in *AutoscalerResource) DeepCopy() *AutoscalerResource {
	if in == nil {
		return nil
	}
	out := new(AutoscalerResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerTarget) DeepCopyInto(out *AutoscalerTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerTarget.
func (in *AutoscalerTarget) DeepCopy() *AutoscalerTarget {
	if in == nil {
		return nil
	}
	out := new(AutoscalerTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonResource) DeepCopyInto(out *CommonResource) {
	*out = *in
	out.Min = in.Min.DeepCopy()
	out.Max = in.Max.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonResource.
func (in *CommonResource) DeepCopy() *CommonResource {
	if in == nil {
		return nil
	}
	out := new(CommonResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(ResourceSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(ResourceSettings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsSettings) DeepCopyInto(out *LimitsSettings) {
	*out = *in
	in.CommonResource.DeepCopyInto(&out.CommonResource)
	out.LimitRequestRatio = in.LimitRequestRatio.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsSettings.
func (in *LimitsSettings) DeepCopy() *LimitsSettings {
	if in == nil {
		return nil
	}
	out := new(LimitsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryBumpUp) DeepCopyInto(out *MemoryBumpUp) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryBumpUp.
func (in *MemoryBumpUp) DeepCopy() *MemoryBumpUp {
	if in == nil {
		return nil
	}
	out := new(MemoryBumpUp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oom) DeepCopyInto(out *Oom) {
	*out = *in
	if in.MemoryBumpUp != nil {
		in, out := &in.MemoryBumpUp, &out.MemoryBumpUp
		*out = new(MemoryBumpUp)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oom.
func (in *Oom) DeepCopy() *Oom {
	if in == nil {
		return nil
	}
	out := new(Oom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchTargetRef) DeepCopyInto(out *PatchTargetRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchTargetRef.
func (in *PatchTargetRef) DeepCopy() *PatchTargetRef {
	if in == nil {
		return nil
	}
	out := new(PatchTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodScheduling) DeepCopyInto(out *PodScheduling) {
	*out = *in
	if in.InstanceCategories != nil {
		in, out := &in.InstanceCategories, &out.InstanceCategories
		*out = new(PodSchedulingInstanceCategories)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodScheduling.
func (in *PodScheduling) DeepCopy() *PodScheduling {
	if in == nil {
		return nil
	}
	out := new(PodScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSchedulingInstanceCategories) DeepCopyInto(out *PodSchedulingInstanceCategories) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(PodSchedulingNodeAffinity)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSchedulingInstanceCategories.
func (in *PodSchedulingInstanceCategories) DeepCopy() *PodSchedulingInstanceCategories {
	if in == nil {
		return nil
	}
	out := new(PodSchedulingInstanceCategories)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSchedulingNodeAffinity) DeepCopyInto(out *PodSchedulingNodeAffinity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSchedulingNodeAffinity.
func (in *PodSchedulingNodeAffinity) DeepCopy() *PodSchedulingNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(PodSchedulingNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reliability) DeepCopyInto(out *Reliability) {
	*out = *in
	if in.Oom != nil {
		in, out := &in.Oom, &out.Oom
		*out = new(Oom)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reliability.
func (in *Reliability) DeepCopy() *Reliability {
	if in == nil {
		return nil
	}
	out := new(Reliability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestsSettings) DeepCopyInto(out *RequestsSettings) {
	*out = *in
	in.CommonResource.DeepCopyInto(&out.CommonResource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestsSettings.
func (in *RequestsSettings) DeepCopy() *RequestsSettings {
	if in == nil {
		return nil
	}
	out := new(RequestsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSettings) DeepCopyInto(out *ResourceSettings) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(RequestsSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LimitsSettings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSettings.
func (in *ResourceSettings) DeepCopy() *ResourceSettings {
	if in == nil {
		return nil
	}
	out := new(ResourceSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleOptions) DeepCopyInto(out *ScheduleOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleOptions.
func (in *ScheduleOptions) DeepCopy() *ScheduleOptions {
	if in == nil {
		return nil
	}
	out := new(ScheduleOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Threshold) DeepCopyInto(out *Threshold) {
	*out = *in
	if in.MinPercentChange != nil {
		in, out := &in.MinPercentChange, &out.MinPercentChange
		*out = new(int32)
		**out = **in
	}
	out.MinUnitChange = in.MinUnitChange.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Threshold.
func (in *Threshold) DeepCopy() *Threshold {
	if in == nil {
		return nil
	}
	out := new(Threshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Thresholds) DeepCopyInto(out *Thresholds) {
	{
		in := &in
		*out = make(Thresholds, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Thresholds.
func (in Thresholds) DeepCopy() Thresholds {
	if in == nil {
		return nil
	}
	out := new(Thresholds)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Workload) DeepCopyInto(out *Workload) {
	{
		in := &in
		*out = make(Workload, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in Workload) DeepCopy() Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOptimizer) DeepCopyInto(out *WorkloadOptimizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOptimizer.
func (in *WorkloadOptimizer) DeepCopy() *WorkloadOptimizer {
	if in == nil {
		return nil
	}
	out := new(WorkloadOptimizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadOptimizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOptimizerList) DeepCopyInto(out *WorkloadOptimizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadOptimizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOptimizerList.
func (in *WorkloadOptimizerList) DeepCopy() *WorkloadOptimizerList {
	if in == nil {
		return nil
	}
	out := new(WorkloadOptimizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadOptimizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOptimizerSpec) DeepCopyInto(out *WorkloadOptimizerSpec) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(TargetRef)
		**out = **in
	}
	if in.PatchTargetRef != nil {
		in, out := &in.PatchTargetRef, &out.PatchTargetRef
		*out = new(PatchTargetRef)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = make(Workload, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Apply != nil {
		in, out := &in.Apply, &out.Apply
		*out = new(Apply)
		**out = **in
	}
	if in.Reliability != nil {
		in, out := &in.Reliability, &out.Reliability
		*out = new(Reliability)
		(*in).DeepCopyInto(*out)
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Autoscaler != nil {
		in, out := &in.Autoscaler, &out.Autoscaler
		*out = new(Autoscaler)
		(*in).DeepCopyInto(*out)
	}
	if in.PodScheduling != nil {
		in, out := &in.PodScheduling, &out.PodScheduling
		*out = new(PodScheduling)
		(*in).DeepCopyInto(*out)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(Thresholds, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOptimizerSpec.
func (in *WorkloadOptimizerSpec) DeepCopy() *WorkloadOptimizerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadOptimizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOptimizerStatus) DeepCopyInto(out *WorkloadOptimizerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOptimizerStatus.
func (in *WorkloadOptimizerStatus) DeepCopy() *WorkloadOptimizerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadOptimizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSettings) DeepCopyInto(out *WorkloadSettings) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSettings.
func (in *WorkloadSettings) DeepCopy() *WorkloadSettings {
	if in == nil {
		return nil
	}
	out := new(WorkloadSettings)
	in.DeepCopyInto(out)
	return out
}
