/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	optimizev1 "github.com/thestormforge/agent-go/pkg/api/optimize/v1"
	applyconfigurationsoptimizev1 "github.com/thestormforge/agent-go/pkg/applyconfigurations/optimize/v1"
	scheme "github.com/thestormforge/agent-go/pkg/stormforge/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkloadOptimizersGetter has a method to return a WorkloadOptimizerInterface.
// A group's client should implement this interface.
type WorkloadOptimizersGetter interface {
	WorkloadOptimizers(namespace string) WorkloadOptimizerInterface
}

// WorkloadOptimizerInterface has methods to work with WorkloadOptimizer resources.
type WorkloadOptimizerInterface interface {
	Create(ctx context.Context, workloadOptimizer *optimizev1.WorkloadOptimizer, opts metav1.CreateOptions) (*optimizev1.WorkloadOptimizer, error)
	Update(ctx context.Context, workloadOptimizer *optimizev1.WorkloadOptimizer, opts metav1.UpdateOptions) (*optimizev1.WorkloadOptimizer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workloadOptimizer *optimizev1.WorkloadOptimizer, opts metav1.UpdateOptions) (*optimizev1.WorkloadOptimizer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*optimizev1.WorkloadOptimizer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*optimizev1.WorkloadOptimizerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *optimizev1.WorkloadOptimizer, err error)
	Apply(ctx context.Context, workloadOptimizer *applyconfigurationsoptimizev1.WorkloadOptimizerApplyConfiguration, opts metav1.ApplyOptions) (result *optimizev1.WorkloadOptimizer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, workloadOptimizer *applyconfigurationsoptimizev1.WorkloadOptimizerApplyConfiguration, opts metav1.ApplyOptions) (result *optimizev1.WorkloadOptimizer, err error)
	WorkloadOptimizerExpansion
}

// workloadOptimizers implements WorkloadOptimizerInterface
type workloadOptimizers struct {
	*gentype.ClientWithListAndApply[*optimizev1.WorkloadOptimizer, *optimizev1.WorkloadOptimizerList, *applyconfigurationsoptimizev1.WorkloadOptimizerApplyConfiguration]
}

// newWorkloadOptimizers returns a WorkloadOptimizers
func newWorkloadOptimizers(c *OptimizeV1Client, namespace string) *workloadOptimizers {
	return &workloadOptimizers{
		gentype.NewClientWithListAndApply[*optimizev1.WorkloadOptimizer, *optimizev1.WorkloadOptimizerList, *applyconfigurationsoptimizev1.WorkloadOptimizerApplyConfiguration](
			"workloadoptimizers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *optimizev1.WorkloadOptimizer { return &optimizev1.WorkloadOptimizer{} },
			func() *optimizev1.WorkloadOptimizerList { return &optimizev1.WorkloadOptimizerList{} },
		),
	}
}
