/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AutoscalerIdentifierApplyConfiguration represents a declarative configuration of the AutoscalerIdentifier type for use
// with apply.
//
// Use new type here so we can disregard the methods associated with MetricIdentifier
// // the hpav2.MetricIdentifier.String() was giving me grief
// AutoscalerIdentifier contains the identifiers for metrics.
type AutoscalerIdentifierApplyConfiguration struct {
	// name is the name of the given metric
	Name *string `json:"name,omitempty"`
	// selector is the string-encoded form of a standard kubernetes label selector for the given metric
	// When set, it is passed as an additional parameter to the metrics server for more specific metrics scoping.
	// When unset, just the metricName will be used to gather metrics.
	Selector *metav1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
}

// AutoscalerIdentifierApplyConfiguration constructs a declarative configuration of the AutoscalerIdentifier type for use with
// apply.
func AutoscalerIdentifier() *AutoscalerIdentifierApplyConfiguration {
	return &AutoscalerIdentifierApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AutoscalerIdentifierApplyConfiguration) WithName(value string) *AutoscalerIdentifierApplyConfiguration {
	b.Name = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *AutoscalerIdentifierApplyConfiguration) WithSelector(value *metav1.LabelSelectorApplyConfiguration) *AutoscalerIdentifierApplyConfiguration {
	b.Selector = value
	return b
}
