/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v2 "k8s.io/api/autoscaling/v2"
)

// AutoscalerTargetApplyConfiguration represents a declarative configuration of the AutoscalerTarget type for use
// with apply.
type AutoscalerTargetApplyConfiguration struct {
	Type      *v2.MetricTargetType `json:"type,omitempty"`
	Min       *int                 `json:"min,omitempty"`
	Max       *int                 `json:"max,omitempty"`
	PatchPath *string              `json:"patchPath,omitempty"`
}

// AutoscalerTargetApplyConfiguration constructs a declarative configuration of the AutoscalerTarget type for use with
// apply.
func AutoscalerTarget() *AutoscalerTargetApplyConfiguration {
	return &AutoscalerTargetApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AutoscalerTargetApplyConfiguration) WithType(value v2.MetricTargetType) *AutoscalerTargetApplyConfiguration {
	b.Type = &value
	return b
}

// WithMin sets the Min field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Min field is set to the value of the last call.
func (b *AutoscalerTargetApplyConfiguration) WithMin(value int) *AutoscalerTargetApplyConfiguration {
	b.Min = &value
	return b
}

// WithMax sets the Max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Max field is set to the value of the last call.
func (b *AutoscalerTargetApplyConfiguration) WithMax(value int) *AutoscalerTargetApplyConfiguration {
	b.Max = &value
	return b
}

// WithPatchPath sets the PatchPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PatchPath field is set to the value of the last call.
func (b *AutoscalerTargetApplyConfiguration) WithPatchPath(value string) *AutoscalerTargetApplyConfiguration {
	b.PatchPath = &value
	return b
}
