/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AutoscalerMetricsApplyConfiguration represents a declarative configuration of the AutoscalerMetrics type for use
// with apply.
type AutoscalerMetricsApplyConfiguration struct {
	ContainerResource *AutoscalerContainerResourceApplyConfiguration `json:"containerResource,omitempty"`
	External          *AutoscalerExternalApplyConfiguration          `json:"external,omitempty"`
	Object            *AutoscalerObjectApplyConfiguration            `json:"object,omitempty"`
	Pods              *AutoscalerPodsApplyConfiguration              `json:"pods,omitempty"`
	Resource          *AutoscalerResourceApplyConfiguration          `json:"resource,omitempty"`
	Target            *AutoscalerTargetApplyConfiguration            `json:"target,omitempty"`
}

// AutoscalerMetricsApplyConfiguration constructs a declarative configuration of the AutoscalerMetrics type for use with
// apply.
func AutoscalerMetrics() *AutoscalerMetricsApplyConfiguration {
	return &AutoscalerMetricsApplyConfiguration{}
}

// WithContainerResource sets the ContainerResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerResource field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithContainerResource(value *AutoscalerContainerResourceApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.ContainerResource = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithExternal(value *AutoscalerExternalApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.External = value
	return b
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithObject(value *AutoscalerObjectApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.Object = value
	return b
}

// WithPods sets the Pods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pods field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithPods(value *AutoscalerPodsApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.Pods = value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithResource(value *AutoscalerResourceApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.Resource = value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *AutoscalerMetricsApplyConfiguration) WithTarget(value *AutoscalerTargetApplyConfiguration) *AutoscalerMetricsApplyConfiguration {
	b.Target = value
	return b
}
