/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AutoscalerContainerResourceApplyConfiguration represents a declarative configuration of the AutoscalerContainerResource type for use
// with apply.
type AutoscalerContainerResourceApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Container *string `json:"container,omitempty"`
}

// AutoscalerContainerResourceApplyConfiguration constructs a declarative configuration of the AutoscalerContainerResource type for use with
// apply.
func AutoscalerContainerResource() *AutoscalerContainerResourceApplyConfiguration {
	return &AutoscalerContainerResourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AutoscalerContainerResourceApplyConfiguration) WithName(value string) *AutoscalerContainerResourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *AutoscalerContainerResourceApplyConfiguration) WithContainer(value string) *AutoscalerContainerResourceApplyConfiguration {
	b.Container = &value
	return b
}
