/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// OomApplyConfiguration represents a declarative configuration of the Oom type for use
// with apply.
type OomApplyConfiguration struct {
	MemoryBumpUp *MemoryBumpUpApplyConfiguration `json:"memoryBumpUp,omitempty"`
}

// OomApplyConfiguration constructs a declarative configuration of the Oom type for use with
// apply.
func Oom() *OomApplyConfiguration {
	return &OomApplyConfiguration{}
}

// WithMemoryBumpUp sets the MemoryBumpUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryBumpUp field is set to the value of the last call.
func (b *OomApplyConfiguration) WithMemoryBumpUp(value *MemoryBumpUpApplyConfiguration) *OomApplyConfiguration {
	b.MemoryBumpUp = value
	return b
}
