/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	optimizev1 "github.com/thestormforge/agent-go/pkg/api/optimize/v1"
)

// PodSchedulingApplyConfiguration represents a declarative configuration of the PodScheduling type for use
// with apply.
type PodSchedulingApplyConfiguration struct {
	SchedulingOptimizationPolicy *optimizev1.PodSchedulingOptimizationPolicy        `json:"schedulingOptimizationPolicy,omitempty"`
	InstanceCategories           *PodSchedulingInstanceCategoriesApplyConfiguration `json:"instanceCategories,omitempty"`
}

// PodSchedulingApplyConfiguration constructs a declarative configuration of the PodScheduling type for use with
// apply.
func PodScheduling() *PodSchedulingApplyConfiguration {
	return &PodSchedulingApplyConfiguration{}
}

// WithSchedulingOptimizationPolicy sets the SchedulingOptimizationPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingOptimizationPolicy field is set to the value of the last call.
func (b *PodSchedulingApplyConfiguration) WithSchedulingOptimizationPolicy(value optimizev1.PodSchedulingOptimizationPolicy) *PodSchedulingApplyConfiguration {
	b.SchedulingOptimizationPolicy = &value
	return b
}

// WithInstanceCategories sets the InstanceCategories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceCategories field is set to the value of the last call.
func (b *PodSchedulingApplyConfiguration) WithInstanceCategories(value *PodSchedulingInstanceCategoriesApplyConfiguration) *PodSchedulingApplyConfiguration {
	b.InstanceCategories = value
	return b
}
