/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	optimizev1 "github.com/thestormforge/agent-go/pkg/api/optimize/v1"
)

// ResourceSettingsApplyConfiguration represents a declarative configuration of the ResourceSettings type for use
// with apply.
type ResourceSettingsApplyConfiguration struct {
	Policy   *optimizev1.Policy                  `json:"optimizationPolicy,omitempty"`
	Requests *RequestsSettingsApplyConfiguration `json:"requests,omitempty"`
	Limits   *LimitsSettingsApplyConfiguration   `json:"limits,omitempty"`
}

// ResourceSettingsApplyConfiguration constructs a declarative configuration of the ResourceSettings type for use with
// apply.
func ResourceSettings() *ResourceSettingsApplyConfiguration {
	return &ResourceSettingsApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ResourceSettingsApplyConfiguration) WithPolicy(value optimizev1.Policy) *ResourceSettingsApplyConfiguration {
	b.Policy = &value
	return b
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *ResourceSettingsApplyConfiguration) WithRequests(value *RequestsSettingsApplyConfiguration) *ResourceSettingsApplyConfiguration {
	b.Requests = value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *ResourceSettingsApplyConfiguration) WithLimits(value *LimitsSettingsApplyConfiguration) *ResourceSettingsApplyConfiguration {
	b.Limits = value
	return b
}
