/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ThresholdApplyConfiguration represents a declarative configuration of the Threshold type for use
// with apply.
type ThresholdApplyConfiguration struct {
	MinPercentChange *int32             `json:"minPercentChange,omitempty"`
	MinUnitChange    *resource.Quantity `json:"minUnitChange,omitempty"`
}

// ThresholdApplyConfiguration constructs a declarative configuration of the Threshold type for use with
// apply.
func Threshold() *ThresholdApplyConfiguration {
	return &ThresholdApplyConfiguration{}
}

// WithMinPercentChange sets the MinPercentChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinPercentChange field is set to the value of the last call.
func (b *ThresholdApplyConfiguration) WithMinPercentChange(value int32) *ThresholdApplyConfiguration {
	b.MinPercentChange = &value
	return b
}

// WithMinUnitChange sets the MinUnitChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinUnitChange field is set to the value of the last call.
func (b *ThresholdApplyConfiguration) WithMinUnitChange(value resource.Quantity) *ThresholdApplyConfiguration {
	b.MinUnitChange = &value
	return b
}
