/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// WorkloadGroupApplyConfiguration represents a declarative configuration of the WorkloadGroup type for use
// with apply.
//
// WorkloadGroup configures which workloads are aggregated together when computing
// this workload's recommendation. Identity fields default to this workload's own
// values; all fields combine to narrow the set of matches.
type WorkloadGroupApplyConfiguration struct {
	// Selector is a Kubernetes label selector matching workloads to include (e.g. "app=nginx").
	Selector *string `json:"selector,omitempty"`
	// Expression is a CEL expression matching workloads to include. The `target`
	// variable refers to this workload and `candidate` to the workload being matched.
	Expression *string `json:"expression,omitempty"`
	// Name overrides the workload name to include. Defaults to this workload's name.
	Name *string `json:"name,omitempty"`
	// Cluster overrides the cluster to include. Defaults to this workload's cluster.
	Cluster *string `json:"cluster,omitempty"`
	// Namespace overrides the namespace to include. Defaults to this workload's namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Resource overrides the resource type to include. Defaults to this workload's resource type.
	Resource *string `json:"resource,omitempty"`
	// ExcludeTarget removes this workload from its own group (mirror mode), so only
	// the matched workloads' metrics drive recommendations. Defaults to false.
	ExcludeTarget *bool `json:"excludeTarget,omitempty"`
}

// WorkloadGroupApplyConfiguration constructs a declarative configuration of the WorkloadGroup type for use with
// apply.
func WorkloadGroup() *WorkloadGroupApplyConfiguration {
	return &WorkloadGroupApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithSelector(value string) *WorkloadGroupApplyConfiguration {
	b.Selector = &value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithExpression(value string) *WorkloadGroupApplyConfiguration {
	b.Expression = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithName(value string) *WorkloadGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithCluster(value string) *WorkloadGroupApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithNamespace(value string) *WorkloadGroupApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithResource(value string) *WorkloadGroupApplyConfiguration {
	b.Resource = &value
	return b
}

// WithExcludeTarget sets the ExcludeTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExcludeTarget field is set to the value of the last call.
func (b *WorkloadGroupApplyConfiguration) WithExcludeTarget(value bool) *WorkloadGroupApplyConfiguration {
	b.ExcludeTarget = &value
	return b
}
